language: ruby

sudo: required

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=trinitronx/fastest-servers

install:
  - npm install -g validate-dockerfile

script:
  - docklint Dockerfile
  - bundle exec rake spec
  - "[ \"$(wc -l /tmp/mirrors.txt | awk '{ print $1 }')\" -gt 0 ] && bash -c 'echo -e \"\e[1;92mPASS\e[0m\"; exit 0' || bash -c 'echo -e \"\e[1;31mFAIL\e[0m\"; exit 1'"
after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
  - "[ -e \"~/.docker/config.json\" ] && shred -n 30 -u -z ~/.docker/config.json"

